# version: "1"
# services:
#   backend:
#     image: backendimage:latest
#     ports:
#       - "5000:5000"
#     environment:
#       - PG_HOST=${PG_HOST}
#       - PG_USER=${PG_USER}
#       - PG_DATABASE=${PG_DATABASE}
#       - PG_PASSWORD=${PG_PASSWORD}
#       - PG_PORT=${PG_PORT}
#       - PORT=${PORT}
#   frontend:
#     image: frontendimg:v1
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
