# name: CI/CD EC2

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: List contents of the current directory
#         run: ls -l
#       - name: rsync deployments
#         uses: burnett01/rsync-deployments@6.0.0
#         with:
#           switches: -avzr --delete --exclude=node_modules --exclude=.env
#           path: ./
#           remote_path: ${{ secrets.DEPLOY_PATH }}
#           remote_host: ${{ secrets.DEPLOY_HOST }}
#           remote_user: ${{ secrets.DEPLOY_USER }}
#           remote_key: ${{ secrets.DEPLOY_KEY }}

name: Build and Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/irinamihai150/demoapp .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/irinamihai150/demoapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull and run Docker image on EC2
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_IP }} "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/irinamihai150/demoapp:latest && docker run -d --env-file .env -p 5000:5000 -e PORT=5000 ${{ secrets.DOCKERHUB_USERNAME }}/irinamihai150/demoapp:latest"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_IP: ${{ secrets.EC2_IP }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Logout from Docker
        run: docker logout
