name: Build and Deploy Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ env.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ env.DOCKERHUB_TOKEN }}
        run: |
          echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
          docker build -t "${DOCKERHUB_USERNAME}/irinamihai150/demoapp" .
          docker push "${DOCKERHUB_USERNAME}/irinamihai150/demoapp"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull and run Docker image on EC2
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_IP }} "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/irinamihai150/demoapp:latest && docker run -d --env-file .env -p 5000:5000 -e PORT=5000 ${{ secrets.DOCKERHUB_USERNAME }}/irinamihai150/demoapp:latest"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_IP: ${{ secrets.EC2_IP }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Logout from Docker
        run: docker logout
