name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker login -u ${{ secrets.DOKER_USERNAME }} --password-stdin -p ${{ secrets.DOKER_TOKEN }}
          docker build -t ${{ secrets.DOKER_USERNAME }}/irinamihai150/demoapp:1.0 .
          docker push ${{ secrets.DOKER_USERNAME }}/irinamihai150/demoapp:1.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull and run Docker image on EC2
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_IP }} "docker pull ${{ secrets.DOKER_USERNAME }}/irinamihai150/demoapp:1.0 && docker run -d --env-file .env -p 5000:5000 -e PORT=5000 ${{ secrets.DOKER_USERNAME }}/irinamihai150/demoapp:1.0"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_IP: ${{ secrets.EC2_IP }}
          DOCKER_USERNAME: ${{ secrets.DOKER_USERNAME }}

      - name: Logout from Docker
        run: docker logout
