name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t irinamihai150/backendimage:latest .
          docker push irinamihai150/backendimage:latest

      - name: SSH into EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull Docker Image on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_IP }} 'docker pull irinamihai150/backendimage:latest'

      - name: Run Docker Container on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_IP }} 'docker run -d -p 5000:5000 --env-file .env irinamihai150/backendimage:latest'
